### Website endpoints
### Test GET ('/')
GET http://localhost:3000

### Test GET ('/dashboard')
GET http://localhost:3000/dashboard


### Data endpoints
### Test GET ('/api/data')
GET http://localhost:3000/api/data